"""
Unit tests for end-to-end model training pipeline.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from titanic_survival.config import settings
from titanic_survival.pipelines.training import training_pipeline


def test_training_pipeline_fit(
    sample_training_data: pd.DataFrame, sample_training_labels: np.ndarray
) -> None:
    """Test that end-to-end training pipeline fits on training samples."""
    result = training_pipeline.fit(sample_training_data, sample_training_labels)
    assert result is not None


def test_training_pipeline_predict(
    sample_training_data: pd.DataFrame, sample_training_labels: np.ndarray
) -> None:
    """Test binary predictions generated by fitted end-to-end pipeline."""
    X_train, X_test, y_train, y_test = train_test_split(
        sample_training_data,
        sample_training_labels,
        test_size=settings.training.test_size,
        random_state=settings.common.random_seed,
        stratify=sample_training_labels,
    )

    training_pipeline.fit(X_train, y_train)
    predictions = training_pipeline.predict(X_test)

    # Assert predictions are binary (0 or 1)
    assert all(pred in [0, 1] for pred in predictions)
    assert len(predictions) == len(X_test)


def test_training_pipeline_predict_proba(
    sample_training_data: pd.DataFrame, sample_training_labels: np.ndarray
) -> None:
    """Test probability estimation outputs generated by fitted end-to-end pipeline."""
    X_train, X_test, y_train, y_test = train_test_split(
        sample_training_data,
        sample_training_labels,
        test_size=settings.training.test_size,
        random_state=settings.common.random_seed,
        stratify=sample_training_labels,
    )

    training_pipeline.fit(X_train, y_train)
    probabilities = training_pipeline.predict_proba(X_test)

    # Verify probability bounds [0.0, 1.0]
    assert (probabilities >= 0.0).all() and (probabilities <= 1.0).all()
    # Verify probability distribution sums to 1.0 across classes
    np.testing.assert_array_almost_equal(probabilities.sum(axis=1), 1.0)
