services:
  mlflow:
    image: ai-mlflow:1.0.0
    container_name: ai-mlflow
    restart: unless-stopped
    ports:
      - "5000:5000"
    working_dir: /workspace
    volumes:
      - ../configs/mlflow:/mlflow
    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --backend-store-uri
      - sqlite:////mlflow/mlflow.db
      - --artifacts-destination
      - /mlflow/artifacts
